apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
