
services:
  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - yolo:/data/db

  backend:
    build: ./backend   
    container_name: backend
    ports:
      - "5000:5000"
    environment: 
      DB_URL: mongodb://mongodb:27017/   
    depends_on:
      - database

  frontend:
    build: ./client   
    container_name: frontend
    ports:
      - "3000:80"

volumes:
  yolo:
   name: yolo